name: Build Cores via Docker

on:
  workflow_dispatch:
    inputs:
      recipes:
        type: choice
        description: 'Select which recipes to build'
        options:
          - "all"
          - "classic_armv7_a7"
          - "linux-armv7-neon"
          - "linux-armv7-neon_test"

jobs:
  set-recipes:
    runs-on: ubuntu-latest
    outputs:
      recipes: ${{ steps.set-recipes.outputs.recipes }}
    steps:
    - id: set-recipes
      run: |
        if [ "${{ inputs.recipes }}" == "all" ]; then
          echo "recipes=[\"classic_armv7_a7\",\"linux-armv7-neon\",\"linux-armv7-neon_test\"]" >> $GITHUB_OUTPUT
        else
          echo "recipes=[\"${{ inputs.recipes }}\"]" >> $GITHUB_OUTPUT
        fi
  build:
    needs: set-recipes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        recipe: ${{ fromJson(needs.set-recipes.outputs.recipes) }}
    steps:
    - uses: actions/checkout@v4

    - name: Initialize workspace
      run: make init

    - name: Build the selected recipe
      run: make build/${{ matrix.recipe }}

    - name: Upload the build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RetroArch cores for ${{ matrix.recipe }}
        path: build/${{ matrix.recipe }}/*
        if-no-files-found: error
        retention-days: 90
